name: Deploy to Hugging Face Spaces

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo (with LFS)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Push to HF Space (official pattern + token sanitize)
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          set -e
          USERNAME="Shu8jst"
          SPACE_NAME="mlb-hr-prob-app"

          # 改行や余計な空白を除去（コピー時の末尾改行対策）
          STRIPPED_TOKEN="$(printf %s "$HF_TOKEN" | tr -d '\r\n')"

          # 公式の push 形式（username:token@...）
          # 参考: Hugging Face docs "Managing Spaces with Github Actions"
          git push "https://$USERNAME:${STRIPPED_TOKEN}@huggingface.co/spaces/$USERNAME/$SPACE_NAME" main
