name: Deploy to Hugging Face Spaces (CLI)

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install hub client
        run: pip install --quiet "huggingface_hub>=0.25.0"

      - name: Upload folder to Space (overwrite)
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          HF_SPACE: ${{ secrets.HF_SPACE }}
        run: |
          python - <<'PY'
          import os
          from huggingface_hub import upload_folder
          token = os.environ["HF_TOKEN"].strip()
          space = os.environ["HF_SPACE"].strip()
          upload_folder(
              folder_path=".",
              repo_id=space,
              repo_type="space",
              token=token,
              commit_message="sync from GitHub Actions",
              # .githubなどはSpace側に不要
              ignore_patterns=[".git/*", ".github/*", "**/__pycache__/*"]
          )
          PY
