name: Deploy to Hugging Face Spaces

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure Git and auth header
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config user.email "actions@github.com"
          git config user.name "github-actions[bot]"
          # ここがポイント：トークンをURLに埋め込まず、HFドメインへのHTTPヘッダーに付与
          git config --global http.https://huggingface.co/.extraheader "Authorization: Bearer ${HF_TOKEN}"

      - name: Push to HF Space
        env:
          HF_SPACE: ${{ secrets.HF_SPACE }}  # 例: Shu8jst/mlb-hr-prob-app
        run: |
          set -e
          # 通常のURLでOK（トークンはextraheaderで送られる）
          git push --force "https://huggingface.co/spaces/${HF_SPACE}" HEAD:main
