name: Deploy to Hugging Face Spaces

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo (with LFS)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Push to HF Space (force overwrite Space from GitHub)
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          set -e
          USERNAME="Shu8jst"
          SPACE_NAME="mlb-hr-prob-app"
          STRIPPED_TOKEN="$(printf %s "$HF_TOKEN" | tr -d '\r\n')"

          # Space 側の main を GitHub の main で上書き（--force）
          git push --force "https://$USERNAME:${STRIPPED_TOKEN}@huggingface.co/spaces/$USERNAME/$SPACE_NAME" HEAD:main
